version: 2

sources:
  - name: raw
    schema : gz_raw_data
    tables:
      - name: product
        identifier: raw_gz_product
        description: products of Greenweez / we have on row per product_id and purchase_price
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have on row per product_id found in each orders_id
      - name: ship
        identifier: raw_gz_ship
        description: ship of Greenweez / we have all shipping info (order_id,shipping_fee, logCost, ship_cost)
