version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: product
        identifier: raw_gz_product
        description: Products of Greenweez / one row per product_id and purchase_price.
        columns: 
          - name: products_id
            description: Catalogue identifiant de produits (primary key).
            tests: 
              - unique  
              - not_null

      - name: sales
        identifier: raw_gz_sales
        description: Sales of Greenweez / one row per product_id found in each orders_id.
        freshness:
          warn_after: 
            count: 90
            period: day
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        tests:
          - unique:
              column_name: "(orders_id || '_' || pdt_id)"

      - name: ship
        identifier: raw_gz_ship
        description: Shipping info of Greenweez / includes order_id, shipping_fee, logCost, ship_cost.
        columns: 
          - name: orders_id
            description: Identifiant de commandes (primary key).
            tests: 
              - unique  
              - not_null  

models:
  - name: int_orders_margin
    description: Orders margin details.
    columns:
      - name: orders_id
        description: Primary key.
        tests:
          - unique
          - not_null

  - name: int_orders_operational
    description: Orders operational margin details.
    columns:
      - name: orders_id
        description: Primary key.
        tests:
          - unique
          - not_null

  - name: int_sales_margin
    description: Sales margin details.
    columns:
      - name: orders_id
        description: Identifiant de commande.
        tests:
          - not_null

  - name: finance_days
    description: Finance days info.
    columns:
      - name: date_date
        description: Primary key.
        tests:
          - unique
          - not_null