version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: product
        identifier: raw_gz_product
        description: Products of Greenweez / one row per product_id and purchase_price.
        columns: 
          - name: products_id
            description: Catalogue identifiant de produits (primary key).
            tests: 
              - unique  
              - not_null

      - name: sales
        identifier: raw_gz_sales
        description: Sales of Greenweez / one row per product_id found in each orders_id.
        freshness:
          warn_after: 
            count: 90
            period: day
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        tests:
          - unique:
              column_name: "(orders_id || '_' || pdt_id)"

      - name: ship
        identifier: raw_gz_ship
        description: Shipping info of Greenweez / includes order_id, shipping_fee, logCost, ship_cost.
        columns: 
          - name: orders_id
            description: Identifiant de commandes (primary key).
            tests: 
              - unique  
              - not_null  

      - name: Adwords
        identifier: raw_gz_adwords
        description: Adwords campaign
        columns: 
          - name: date_date
            description: date de la campagne Adwords
          - name: paid_source
            description: source de paiement Adwords
          - name: campaign_key
            description: identifiant de la campagne Adwords
          - name: camPGN_name
            description: nom de la campagne Adwords
          - name: ads_cost
            description: coût de la campagne Adwords
          - name: impression
            description: coût d'impression de la campagne Adwords
          - name: click
            description: coût par click de la campagne Adwords
        tests:
          - unique:
              column_name: "( camPGN_name|| '_' || date_date)"  

      - name: Bing
        identifier: raw_gz_bing
        description: Bing campaign
        columns: 
          - name: date_date
            description: date de la campagne Bing
          - name: paid_source
            description: source de paiement Bing
          - name: campaign_key
            description: identifiant de la campagne Bing
          - name: camPGN_name
            description: nom de la campagne Bing
          - name: ads_cost
            description: coût de la campagne Bing
          - name: impression
            description: coût d'impression de la campagne Bing
          - name: click
            description: coût par click de la campagne Bing
        tests:
          - unique:
              column_name: "( camPGN_name|| '_' || date_date)"  

      - name: Criteo
        identifier: raw_gz_criteo
        description: Criteo campaign
        columns: 
          - name: date_date
            description: date de la campagne Criteo
          - name: paid_source
            description: source de paiement Criteo
          - name: campaign_key
            description: identifiant de la campagne Criteo
          - name: camPGN_name
            description: nom de la campagne Criteo
          - name: ads_cost
            description: coût de la campagne Criteo
          - name: impression
            description: coût d'impression de la campagne Criteo
          - name: click
            description: coût par click de la campagne Criteo
        tests:
          - unique:
              column_name: "( camPGN_name|| '_' || date_date)"  

      - name: Facebook
        identifier: raw_gz_facebook
        description: Facebook campaign
        columns: 
          - name: date_date
            description: date de la campagne Facebook
          - name: paid_source
            description: source de paiement Facebook
          - name: campaign_key
            description: identifiant de la campagne Facebook
          - name: camPGN_name
            description: nom de la campagne Facebook
          - name: ads_cost
            description: coût de la campagne Facebook
          - name: impression
            description: coût d'impression de la campagne Facebook
          - name: click
            description: coût par click de la campagne Facebook
        tests:
          - unique:
              column_name: "( camPGN_name|| '_' || date_date)"  



models:
  - name: int_orders_margin
    description: Orders margin details.
    columns:
      - name: orders_id
        description: Primary key.
        tests:
          - unique
          - not_null

  - name: int_orders_operational
    description: Orders operational margin details.
    columns:
      - name: orders_id
        description: Primary key.
        tests:
          - unique
          - not_null

  - name: int_sales_margin
    description: Sales margin details.
    columns:
      - name: orders_id
        description: Identifiant de commande.
        tests:
          - not_null

  - name: finance_days
    description: Finance days info.
    columns:
      - name: date_date
        description: Primary key.
        tests:
          - unique
          - not_null

  - name: int_campaigns
    description: Jointure de toutes les infos campaign dans un même dataset 
    columns:
      - name: "( camPGN_name|| '_' || date_date)" 
        description: Primary key.
        tests:
          - unique
          - not_null

  - name: int_campaigns_day
    description: Jointure de toutes les infos campaign dans un même dataset // par jour
    columns:
      - name: date_date
        description: Primary key.
        tests:
          - unique
          - not_null


